///$tab 60_SUB GetEngineHoursAggr
SUB GetEngineHoursAggregation

[iot_engine_hours_aggregation]:
SELECT 
    "asset_id",
	"aggregate_ts",
	"engine_hours" AS engine_hours_aggr,
	"invalid_data_detected",
	"cumulative_engine_hours_final"
FROM 
	iotv3."iot_engine_hours_aggregation"
WHERE 
	asset_id = $(odag_asset_id) 
AND aggregate_ts BETWEEN $(odag_Start_Date) and $(odag_End_Date);

ENDSUB